/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FanProfile, SecurityAudit } from './types';

/**
 * Enterprise-grade security utilities for PII masking, prompt injection defense,
 * OWASP-compliant output validation, and safety guardrails.
 */
export class SecurityEngine {
  // Regex pattern for email detection
  private static readonly EMAIL_REGEX = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

  // Regex pattern for phone number detection (supports standard, international, and dashed formats)
  private static readonly PHONE_REGEX = /(\+?\d{1,4}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/g;

  // Signatures indicating potential LLM prompt injection attempts
  private static readonly INJECTION_SIGNATURES = [
    /ignore\s+(all\s+)?previous\s+(instructions|rules|directives|prompts)/i,
    /system\s+override/i,
    /you\s+are\s+now\s+an?\s+(admin|stadium admin|system administrator)/i,
    /act\s+as\s+(an?\s+)?(stadium\s+)?admin/i,
    /developer\s+mode/i,
    /bypass\s+restrictions/i,
    /output\s+the\s+system\s+prompt/i,
    /forget\s+rules/i,
    /disable\s+guardrails/i,
    /roleplay\s+as/i,
    /acting\s+as\s+a\s+system\s+administrator/i
  ];

  /**
   * Redacts personal data (names, emails, phones) from an incoming string payload.
   */
  public static redactPII(text: string, fanProfile?: FanProfile): { redactedText: string; count: number } {
    let redactedText = text;
    let count = 0;

    // Redact Emails
    const emailMatches = redactedText.match(this.EMAIL_REGEX);
    if (emailMatches) {
      count += emailMatches.length;
      redactedText = redactedText.replace(this.EMAIL_REGEX, '[REDACTED_EMAIL]');
    }

    // Redact Phone Numbers
    const phoneMatches = redactedText.match(this.PHONE_REGEX);
    if (phoneMatches) {
      count += phoneMatches.length;
      redactedText = redactedText.replace(this.PHONE_REGEX, '[REDACTED_PHONE]');
    }

    // Redact Fan Profile specific names if supplied
    if (fanProfile) {
      if (fanProfile.name && fanProfile.name.trim().length > 0) {
        const nameRegex = new RegExp(`\\b${this.escapeRegExp(fanProfile.name)}\\b`, 'gi');
        const nameMatches = redactedText.match(nameRegex);
        if (nameMatches) {
          count += nameMatches.length;
          redactedText = redactedText.replace(nameRegex, '[REDACTED_NAME]');
        }
      }
      if (fanProfile.email) {
        const emailRegex = new RegExp(this.escapeRegExp(fanProfile.email), 'gi');
        if (redactedText.includes(fanProfile.email)) {
          count++;
          redactedText = redactedText.replace(emailRegex, '[REDACTED_EMAIL]');
        }
      }
      if (fanProfile.phone) {
        const phoneRegex = new RegExp(this.escapeRegExp(fanProfile.phone), 'gi');
        if (redactedText.includes(fanProfile.phone)) {
          count++;
          redactedText = redactedText.replace(phoneRegex, '[REDACTED_PHONE]');
        }
      }
    }

    return { redactedText, count };
  }

  /**
   * Checks a text payload for suspected prompt injection vectors.
   * Throws an error or returns boolean indicating safe status.
   */
  public static detectPromptInjection(text: string): boolean {
    for (const regex of this.INJECTION_SIGNATURES) {
      if (regex.test(text)) {
        return true;
      }
    }
    return false;
  }

  /**
   * Sanitizes strings to protect against Cross-Site Scripting (XSS) in dynamically
   * rendered routing instructions or dashboard elements.
   */
  public static sanitizeHTML(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#x27;')
      .replace(/\//g, '&#x2F;');
  }

  /**
   * Operational Output Guardrail.
   * Checks LLM routing outputs against critical stadium safety conditions.
   * If a route contains a closed or high-hazard point, raises a validation error.
   *
   * @param directionOutput The raw directions text/Markdown generated by the AI
   * @param closedGateIds List of gates currently closed or unsafe
   * @returns true if output passes safety checks, false if it violates stadium parameters
   */
  public static validateSafetyGuardrails(directionOutput: string, closedGateIds: string[]): { isSafe: boolean; warning?: string } {
    const uppercaseOutput = directionOutput.toUpperCase();

    // Check if any of the closed/unsafe gates are recommended as active route points
    for (const gateId of closedGateIds) {
      const normalizedGate = gateId.toUpperCase();
      // e.g. "Gate 4" or "GATE 4"
      if (uppercaseOutput.includes(`GATE ${normalizedGate}`) || uppercaseOutput.includes(`GATE-${normalizedGate}`) || (gateId.length > 2 && uppercaseOutput.includes(normalizedGate))) {
        return {
          isSafe: false,
          warning: `Unsafe operational recommendation: Directed fans toward closed/hazardous facility: ${gateId}`
        };
      }
    }

    // Check for unsafe actions (climbing, breaching queues, jumping railings, bypassing security checks)
    const dangerousPhrases = [
      'CLIMB OVER',
      'JUMP THE RAILING',
      'BYPASS SECURITY CHECKPOINT',
      'IGNORE STAFF INSTRUCTIONS',
      'FORCE ENTRY',
      'BREACH GATE'
    ];

    for (const phrase of dangerousPhrases) {
      if (uppercaseOutput.includes(phrase)) {
        return {
          isSafe: false,
          warning: `Prohibited action detected: AI output contains unsafe instruction: "${phrase}"`
        };
      }
    }

    return { isSafe: true };
  }

  /**
   * Helper to escape characters for dynamic regular expression generation
   */
  private static escapeRegExp(str: string): string {
    return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  /**
   * Audits an operation, returning the structured log.
   */
  public static performAudit(
    originalPayload: string,
    redactedPayload: string,
    piiCount: number,
    hasInjection: boolean
  ): SecurityAudit {
    return {
      originalPayloadLength: originalPayload.length,
      piiRedactedCount: piiCount,
      promptInjectionDetected: hasInjection,
      isSanitized: true,
      timestamp: new Date().toISOString()
    };
  }
}
